runtime: nodejs
env: flex
service: fake-api

env_variables:
  NODE_ENV: production

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

skip_files:
  - \.gitignore
  - ^node_modules/(.*/)?
